server:
  port: 8025
spring:
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nota_service
    username: nota_service
    password: nota_service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    br.com.arquivei: DEBUG

api:
  sandbox-api: https://sandbox-api.arquivei.com.br

feign:
  client:
    config:
      default:
        loggerLevel: full

